version: "3.8"

services:
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: /home/cyferrei/inception/srcs/requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "nc", "-zv", "mariadb", "3306"]
      interval: 1s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:user
    container_name: nginx
    build: /home/cyferrei/inception/srcs/requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: /home/cyferrei/inception/srcs/requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always
    expose:
      - "9000"

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/data/mariadb
      o: bind
      type: none
  wordpress:
    driver: local
    driver_opts:
      device: /home/data/wordpress
      o: bind
      type: none

networks:
  inception:
    name: inception